'use client';
import { useEffect,useState } from 'react';
import Link from 'next/link';

export default function Portal(){
 const [me,setMe]=useState<any>(); const [profile,setProfile]=useState<any>(); const [circles,setCircles]=useState<any[]>([]); const [application,setApplication]=useState<any>(); const [docs,setDocs]=useState<any[]>([]); const [notes,setNotes]=useState<any[]>([]); const [registrations,setRegistrations]=useState<any[]>([]); const [payments,setPayments]=useState<any[]>([]); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [uploading,setUploading]=useState(false);
 async function load(){
  const meRes=await fetch('/backend/api/v1/auth/me'); if(!meRes.ok){setLoading(false);return;} const meData=await meRes.json(); setMe(meData);
  const [p,a,d,n,c,regRes,pay]=await Promise.all([fetch('/backend/api/v1/member/profile'),fetch('/backend/api/v1/member/application'),fetch('/backend/api/v1/member/documents'),fetch('/backend/api/v1/member/notifications'),fetch('/backend/api/v1/public/circles'),fetch('/backend/api/v1/events/registrations/me'),fetch('/backend/api/v1/member/payments')]);
  if(p.ok)setProfile(await p.json()); if(a.ok)setApplication(await a.json()); if(d.ok)setDocs(await d.json()); if(n.ok)setNotes(await n.json()); if(c.ok)setCircles(await c.json()); if(regRes.ok)setRegistrations(await regRes.json()); if(pay.ok)setPayments(await pay.json()); setLoading(false);
 }
 useEffect(()=>{load()},[]);
 async function saveProfile(e:React.FormEvent){e.preventDefault();if(!profile)return;setSaving(true);const r=await fetch('/backend/api/v1/member/profile',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(profile)});if(r.ok){alert('প্রোফাইল সংরক্ষণ হয়েছে।');load()}else alert((await r.json().catch(()=>null))?.detail||'প্রোফাইল সংরক্ষণ ব্যর্থ');setSaving(false)}
 async function submitApplication(){const r=await fetch('/backend/api/v1/member/application',{method:'POST'});if(r.ok){setApplication(await r.json());alert('আবেদন জমা হয়েছে।')}else alert((await r.json().catch(()=>null))?.detail||'আবেদন জমা দেওয়া যায়নি।')}
 async function upload(e:React.ChangeEvent<HTMLInputElement>,type:string){const file=e.target.files?.[0];if(!file)return;setUploading(true);const fd=new FormData();fd.append('file',file);const r=await fetch(`/backend/api/v1/member/documents?document_type=${type}`,{method:'POST',body:fd});if(r.ok){const newDoc=await r.json();setDocs(prev=>[newDoc,...prev]);}else alert((await r.json().catch(()=>null))?.detail||'আপলোড ব্যর্থ');setUploading(false);e.target.value='';}
 if(loading)return <section className="section"><div className="container">লোড হচ্ছে...</div></section>;
 if(!me)return <section className="section"><div className="container narrow"><div className="card card-body"><h1>সদস্য পোর্টাল</h1><p className="muted">প্রবেশ করতে লগইন করুন।</p><Link className="btn btn-primary" href="/login">Login</Link></div></div></section>;
 return <section className="section"><div className="container"><div className="section-head left"><span className="eyebrow">MEMBER PORTAL</span><h1>স্বাগতম, {me.name_bn}</h1><p>সদস্যতা, আবেদন, প্রোফাইল, নথি ও ডিজিটাল কার্ড পরিচালনা করুন।</p><div className="row-actions"><Link className="btn btn-light" href="/portal/security">সেশন ও নিরাপত্তা</Link></div></div>
   <div className="grid-4"><div className="card card-body"><span className="kicker green">MEMBERSHIP</span><h2>{me.membership_id||'Pending'}</h2><span className="status-pill">{me.membership_status||'PENDING'}</span></div><div className="card card-body"><span className="kicker blue">CIRCLE</span><h2>{me.circle_bn||'Not assigned'}</h2><p className="muted">{me.designation_bn||'Designation not set'}</p></div><div className="card card-body"><span className="kicker orange">DIGITAL CARD</span><h3>{me.membership_status==='ACTIVE'?'Ready':'Available after approval'}</h3>{me.membership_status==='ACTIVE'&&<div className="row-actions"><a className="btn btn-blue" href="/backend/api/v1/member/card" target="_blank" download>PNG</a><a className="btn btn-light" href="/backend/api/v1/member/card/pdf" target="_blank" download>PDF</a></div>}</div><div className="card card-body"><span className="kicker red">NOTIFICATIONS</span><h2>{notes.filter(n=>!n.read_at).length}</h2><p className="muted">Unread notifications</p></div></div>
   {me.membership_status==='ACTIVE'&&<div className="card card-body" style={{marginTop:20}}><div className="split-head"><div><span className="kicker green">DIGITAL CREDENTIAL</span><h2>অফিসিয়াল ডিজিটাল পরিচয়পত্র (ID Card)</h2></div><div className="row-actions"><a className="btn btn-primary" href="/backend/api/v1/member/card" target="_blank" download>ডাউনলোড PNG</a><a className="btn btn-light" href="/backend/api/v1/member/card/pdf" target="_blank" download>মুদ্রণযোগ্য PDF</a></div></div><div style={{marginTop:15,borderRadius:12,overflow:'hidden',border:'2px solid rgba(245, 158, 11, 0.4)',maxWidth:620}}><img src="/backend/api/v1/member/card" alt="Digital ID Card Preview" style={{width:'100%',height:'auto',display:'block'}}/></div></div>}
   <div className="portal-grid" style={{marginTop:20}}>
    <div className="card card-body"><div className="split-head"><div><span className="kicker blue">PROFILE</span><h2>সদস্য প্রোফাইল</h2></div></div><form onSubmit={saveProfile} className="form-grid">{[['name_bn','বাংলা নাম'],['name_en','ইংরেজি নাম'],['phone','মোবাইল'],['designation_bn','পদবি'],['designation_en','Designation'],['employee_id','Employee ID'],['diploma_institution','ডিপ্লোমা প্রতিষ্ঠান'],['graduation_year','পাসের বছর'],['nid_number','NID নম্বর']].map(([key,label])=><input key={key} placeholder={label} required={['name_bn'].includes(key)} value={profile?.[key]??''} onChange={e=>setProfile({...profile,[key]:e.target.value})}/>)}<select value={profile?.circle_id??''} onChange={e=>setProfile({...profile,circle_id:e.target.value?Number(e.target.value):null})}><option value="">গ্রিড সার্কেল নির্বাচন</option>{circles.map(c=><option key={c.id} value={c.id}>{c.name_bn}</option>)}</select><textarea className="span-2" rows={3} placeholder="বর্তমান ঠিকানা" value={profile?.current_address??''} onChange={e=>setProfile({...profile,current_address:e.target.value})}/><textarea className="span-2" rows={3} placeholder="স্থায়ী ঠিকানা" value={profile?.permanent_address??''} onChange={e=>setProfile({...profile,permanent_address:e.target.value})}/><button className="btn btn-primary span-2" disabled={saving}>{saving?'সংরক্ষণ হচ্ছে...':'প্রোফাইল সংরক্ষণ'}</button></form></div>
    <div className="card card-body"><div className="split-head"><div><span className="kicker green">APPLICATION</span><h2>সদস্য আবেদন</h2></div><span className="status-pill">{application?.status}</span></div><p className="muted">প্রোফাইল ও প্রয়োজনীয় নথি সম্পূর্ণ করার পর আবেদন জমা দিন।</p><button className="btn btn-green" onClick={submitApplication} disabled={['SUBMITTED','UNDER_REVIEW','ACTIVE'].includes(application?.status)}>{application?.status==='ACTIVE'?'অনুমোদিত':application?.status==='SUBMITTED'?'পর্যালোচনার অপেক্ষায়':'আবেদন জমা দিন'}</button><hr/><div><span className="kicker blue">DOCUMENTS</span><h3>নথি আপলোড</h3><div className="upload-grid"><label className="upload-box">NID<input type="file" accept="image/*,application/pdf" hidden onChange={e=>upload(e,'NID')}/></label><label className="upload-box">Certificate<input type="file" accept="image/*,application/pdf" hidden onChange={e=>upload(e,'CERTIFICATE')}/></label><label className="upload-box">Photo<input type="file" accept="image/*" hidden onChange={e=>upload(e,'PHOTO')}/></label></div>{uploading&&<p className="muted small">আপলোড হচ্ছে...</p>}<div className="doc-list">{docs.map(d=><div key={d.id}><span>{d.document_type}</span><span>{d.filename}</span><span className="status-pill">{d.review_status}</span></div>)}</div></div></div>
   </div>
   <div className="portal-grid" style={{marginTop:20}}><div className="card card-body"><span className="kicker orange">MY EVENTS</span><h2>ইভেন্ট নিবন্ধন</h2>{registrations.length?registrations.map(r=><div className="timeline-item" key={r.id}><strong>Ticket: {r.ticket_code}</strong><p>Registration: {r.registration_status} · Attendance: {r.attendance_status} · Payment: {r.payment_status}</p><a className="btn btn-light" href={`/events/ticket/${encodeURIComponent(r.ticket_token||r.ticket_code)}`}>টিকিট দেখুন</a></div>):<p className="muted">কোনো ইভেন্ট নিবন্ধন নেই।</p>}</div><div className="card card-body"><span className="kicker green">PAYMENTS</span><h2>পেমেন্ট ইতিহাস</h2>{payments.length?payments.slice(0,8).map(p=><div className="timeline-item" key={p.id}><strong>{p.purpose} · {p.amount} {p.currency}</strong><p>{p.provider} · {p.status} {p.transaction_ref?`· ${p.transaction_ref}`:''}</p></div>):<p className="muted">কোনো পেমেন্ট রেকর্ড নেই।</p>}</div></div><div className="card card-body" style={{marginTop:20}}><span className="kicker blue">NOTIFICATIONS</span><h2>সাম্প্রতিক বার্তা</h2>{notes.length?notes.slice(0,8).map(n=><div className="timeline-item" key={n.id}><strong>{n.title_bn}</strong><p>{n.body_bn}</p><small className="muted">{new Date(n.created_at).toLocaleString('bn-BD')}</small></div>):<p className="muted">কোনো নতুন নোটিফিকেশন নেই।</p>}</div>
 </div></section>
}
