'use client';
import Link from 'next/link';
import { FormEvent, use, useEffect, useState } from 'react';

export default function EventRegister({ params }: { params: Promise<{ id: string }> }) {
  const { id } = use(params);
  const [event, setEvent] = useState<any>(null); const [form, setForm] = useState({name:'',email:'',phone:'',organization:''}); const [result,setResult]=useState<any>(null); const [error,setError]=useState(''); const [busy,setBusy]=useState(false);
  useEffect(()=>{fetch(`/backend/api/v1/event/${id}`).then(r=>r.json()).then(setEvent).catch(()=>setError('Event could not be loaded'));},[id]);
  async function submit(e:FormEvent){e.preventDefault();setBusy(true);setError('');try{const r=await fetch(`/backend/api/v1/events/${id}/registrations`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(form)});const b=await r.json().catch(()=>({}));if(!r.ok)throw new Error(b.detail||'Registration failed');setResult(b);}catch(e:any){setError(e.message||'Registration failed')}finally{setBusy(false)}}
  if(result)return <section className="section"><div className="container narrow"><div className="card card-body"><span className="tag green">REGISTERED</span><h1>নিবন্ধন সম্পন্ন হয়েছে</h1><p className="muted">{event?.title_bn}</p><div className="verify-result"><span className="verified-label">TICKET CODE</span><h2>{result.ticket_code}</h2><p>নিবন্ধনের অবস্থা: <b>{result.registration_status}</b></p><Link className="btn btn-primary" href={`/events/ticket/${encodeURIComponent(result.ticket_token||result.ticket_code)}`}>টিকিট দেখুন</Link></div></div></div></section>;
  return <section className="section"><div className="container narrow-wide"><Link className="back-link" href={`/events/${id}`}>← ইভেন্টে ফিরুন</Link><div className="card card-body"><span className="eyebrow">EVENT REGISTRATION</span><h1>{event?.title_bn||'ইভেন্ট নিবন্ধন'}</h1><p className="muted">আপনার যোগাযোগের তথ্য দিয়ে নিবন্ধন সম্পন্ন করুন।</p>{error&&<div className="notice-error">{error}</div>}<form className="form-grid" onSubmit={submit}><input required minLength={2} placeholder="পূর্ণ নাম *" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><input required type="email" placeholder="ইমেইল *" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/><input placeholder="মোবাইল" value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/><input placeholder="প্রতিষ্ঠান/সংস্থা" value={form.organization} onChange={e=>setForm({...form,organization:e.target.value})}/><button className="btn btn-green span-2" disabled={busy}>{busy?'নিবন্ধন হচ্ছে...':'নিবন্ধন সম্পন্ন করুন'}</button></form></div></div></section>;
}
