"""initial portal schema"""
revision = 'bca12bda0867'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('circles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_bn', sa.String(length=120), nullable=False),
    sa.Column('name_en', sa.String(length=120), nullable=False),
    sa.Column('description_bn', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_circles_active'), 'circles', ['active'], unique=False)
    op.create_index(op.f('ix_circles_name_bn'), 'circles', ['name_bn'], unique=True)
    op.create_table('circulars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('reference_no', sa.String(length=100), nullable=True),
    sa.Column('title_bn', sa.String(length=500), nullable=False),
    sa.Column('title_en', sa.String(length=500), nullable=True),
    sa.Column('summary_bn', sa.Text(), nullable=True),
    sa.Column('document_url', sa.String(length=1000), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_circulars_category'), 'circulars', ['category'], unique=False)
    op.create_index(op.f('ix_circulars_is_published'), 'circulars', ['is_published'], unique=False)
    op.create_index(op.f('ix_circulars_published_at'), 'circulars', ['published_at'], unique=False)
    op.create_index(op.f('ix_circulars_reference_no'), 'circulars', ['reference_no'], unique=False)
    op.create_index(op.f('ix_circulars_title_bn'), 'circulars', ['title_bn'], unique=False)
    op.create_table('contact_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('subject', sa.String(length=300), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contact_messages_email'), 'contact_messages', ['email'], unique=False)
    op.create_index(op.f('ix_contact_messages_status'), 'contact_messages', ['status'], unique=False)
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title_bn', sa.String(length=500), nullable=False),
    sa.Column('title_en', sa.String(length=500), nullable=True),
    sa.Column('description_bn', sa.Text(), nullable=True),
    sa.Column('event_date', sa.DateTime(), nullable=True),
    sa.Column('location_bn', sa.String(length=300), nullable=True),
    sa.Column('cover_image_url', sa.String(length=1000), nullable=True),
    sa.Column('registration_enabled', sa.Boolean(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_event_date'), 'events', ['event_date'], unique=False)
    op.create_index(op.f('ix_events_is_published'), 'events', ['is_published'], unique=False)
    op.create_index(op.f('ix_events_title_bn'), 'events', ['title_bn'], unique=False)
    op.create_table('journals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=False),
    sa.Column('title_bn', sa.String(length=500), nullable=False),
    sa.Column('title_en', sa.String(length=500), nullable=True),
    sa.Column('author', sa.String(length=300), nullable=True),
    sa.Column('edition', sa.String(length=100), nullable=True),
    sa.Column('publication_date', sa.DateTime(), nullable=True),
    sa.Column('abstract_bn', sa.Text(), nullable=True),
    sa.Column('cover_image_url', sa.String(length=1000), nullable=True),
    sa.Column('document_url', sa.String(length=1000), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_journals_category'), 'journals', ['category'], unique=False)
    op.create_index(op.f('ix_journals_is_published'), 'journals', ['is_published'], unique=False)
    op.create_index(op.f('ix_journals_title_bn'), 'journals', ['title_bn'], unique=False)
    op.create_table('site_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=120), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=80), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_site_settings_category'), 'site_settings', ['category'], unique=False)
    op.create_index(op.f('ix_site_settings_key'), 'site_settings', ['key'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('name_bn', sa.String(length=200), nullable=False),
    sa.Column('name_en', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('role', sa.String(length=40), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.String(length=100), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity'), 'audit_logs', ['entity'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('committee_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_bn', sa.String(length=200), nullable=False),
    sa.Column('name_en', sa.String(length=200), nullable=True),
    sa.Column('designation_bn', sa.String(length=200), nullable=False),
    sa.Column('designation_en', sa.String(length=200), nullable=True),
    sa.Column('message_bn', sa.Text(), nullable=True),
    sa.Column('photo_url', sa.String(length=1000), nullable=True),
    sa.Column('circle_id', sa.Integer(), nullable=True),
    sa.Column('term_start', sa.Integer(), nullable=True),
    sa.Column('term_end', sa.Integer(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['circle_id'], ['circles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_committee_members_active'), 'committee_members', ['active'], unique=False)
    op.create_index(op.f('ix_committee_members_circle_id'), 'committee_members', ['circle_id'], unique=False)
    op.create_table('media_assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('media_type', sa.String(length=20), nullable=False),
    sa.Column('title_bn', sa.String(length=500), nullable=False),
    sa.Column('description_bn', sa.Text(), nullable=True),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('thumbnail_url', sa.String(length=1000), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('published', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_media_assets_event_id'), 'media_assets', ['event_id'], unique=False)
    op.create_index(op.f('ix_media_assets_media_type'), 'media_assets', ['media_type'], unique=False)
    op.create_index(op.f('ix_media_assets_published'), 'media_assets', ['published'], unique=False)
    op.create_table('members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('membership_id', sa.String(length=50), nullable=True),
    sa.Column('designation_bn', sa.String(length=200), nullable=True),
    sa.Column('designation_en', sa.String(length=200), nullable=True),
    sa.Column('employee_id', sa.String(length=100), nullable=True),
    sa.Column('diploma_institution', sa.String(length=250), nullable=True),
    sa.Column('graduation_year', sa.Integer(), nullable=True),
    sa.Column('nid_number', sa.String(length=50), nullable=True),
    sa.Column('date_of_birth', sa.DateTime(), nullable=True),
    sa.Column('current_address', sa.Text(), nullable=True),
    sa.Column('permanent_address', sa.Text(), nullable=True),
    sa.Column('photo_url', sa.String(length=1000), nullable=True),
    sa.Column('circle_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('application_note', sa.Text(), nullable=True),
    sa.Column('issue_date', sa.DateTime(), nullable=True),
    sa.Column('validity_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['circle_id'], ['circles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_members_circle_id'), 'members', ['circle_id'], unique=False)
    op.create_index(op.f('ix_members_membership_id'), 'members', ['membership_id'], unique=True)
    op.create_index(op.f('ix_members_status'), 'members', ['status'], unique=False)
    op.create_index(op.f('ix_members_user_id'), 'members', ['user_id'], unique=True)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title_bn', sa.String(length=300), nullable=False),
    sa.Column('body_bn', sa.Text(), nullable=False),
    sa.Column('notification_type', sa.String(length=50), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('member_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('document_type', sa.String(length=50), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('storage_path', sa.String(length=1000), nullable=False),
    sa.Column('content_type', sa.String(length=120), nullable=True),
    sa.Column('review_status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_member_documents_member_id'), 'member_documents', ['member_id'], unique=False)
    op.create_index(op.f('ix_member_documents_review_status'), 'member_documents', ['review_status'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_member_documents_review_status'), table_name='member_documents')
    op.drop_index(op.f('ix_member_documents_member_id'), table_name='member_documents')
    op.drop_table('member_documents')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_members_user_id'), table_name='members')
    op.drop_index(op.f('ix_members_status'), table_name='members')
    op.drop_index(op.f('ix_members_membership_id'), table_name='members')
    op.drop_index(op.f('ix_members_circle_id'), table_name='members')
    op.drop_table('members')
    op.drop_index(op.f('ix_media_assets_published'), table_name='media_assets')
    op.drop_index(op.f('ix_media_assets_media_type'), table_name='media_assets')
    op.drop_index(op.f('ix_media_assets_event_id'), table_name='media_assets')
    op.drop_table('media_assets')
    op.drop_index(op.f('ix_committee_members_circle_id'), table_name='committee_members')
    op.drop_index(op.f('ix_committee_members_active'), table_name='committee_members')
    op.drop_table('committee_members')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_site_settings_key'), table_name='site_settings')
    op.drop_index(op.f('ix_site_settings_category'), table_name='site_settings')
    op.drop_table('site_settings')
    op.drop_index(op.f('ix_journals_title_bn'), table_name='journals')
    op.drop_index(op.f('ix_journals_is_published'), table_name='journals')
    op.drop_index(op.f('ix_journals_category'), table_name='journals')
    op.drop_table('journals')
    op.drop_index(op.f('ix_events_title_bn'), table_name='events')
    op.drop_index(op.f('ix_events_is_published'), table_name='events')
    op.drop_index(op.f('ix_events_event_date'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_contact_messages_status'), table_name='contact_messages')
    op.drop_index(op.f('ix_contact_messages_email'), table_name='contact_messages')
    op.drop_table('contact_messages')
    op.drop_index(op.f('ix_circulars_title_bn'), table_name='circulars')
    op.drop_index(op.f('ix_circulars_reference_no'), table_name='circulars')
    op.drop_index(op.f('ix_circulars_published_at'), table_name='circulars')
    op.drop_index(op.f('ix_circulars_is_published'), table_name='circulars')
    op.drop_index(op.f('ix_circulars_category'), table_name='circulars')
    op.drop_table('circulars')
    op.drop_index(op.f('ix_circles_name_bn'), table_name='circles')
    op.drop_index(op.f('ix_circles_active'), table_name='circles')
    op.drop_table('circles')
    # ### end Alembic commands ###
